version: '2.2'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    command: bundle exec rails s
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/hits-counter_test
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  pgdata:
