version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    command: bundle exec rails s
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  pgdata:
