---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hits-counter
  labels:
    app: hits-counter-app
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hits-counter-app
      tier: app
  template:
    metadata:
      name: hits-counter
      labels:
        app: hits-counter-app
        tier: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/hits-counter-226206/hits-counter:7bf7eb9c099b
        env:
        - name: PORT
          value: "3000"
        ports:
          - containerPort: 3000
