---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hits-counter
  labels:
    app: hits-counter-app
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hits-counter-app
      tier: app
  template:
    metadata:
      name: hits-counter
      labels:
        app: hits-counter-app
        tier: app
    spec:
      containers:
      - name: app
        image: amaksimov/hits-counter:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "app-db-url"
              key: "databaseurl"
        - name: PORT
          value: "3000"
        ports:
          - containerPort: 3000
        imagePullPolicy: Never
