apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 15
  template:
    metadata:
      name: migrate
    spec:
      containers:
      - name: migrate
        image: eu.gcr.io/hits-counter-226206/hits-counter:latest
        command: ["/hits-counter/node_modules/.bin/db-migrate", "up"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "app-db-url"
              key: "databaseurl"
      restartPolicy: Never
