---
apiVersion: v1
kind: Service
metadata:
  name: hits-counter
  labels:
    app: hits-counter-app
spec:
  ports:
    - port: 3000
      name: hits-c-http
  selector:
    app: hits-counter-app
    tier: app
  type: NodePort
