---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hits-counter
  labels:
    app: hits-counter-app
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hits-counter-app
      tier: app
  template:
    metadata:
      name: hits-counter
      labels:
        app: hits-counter-app
        tier: app
    spec:
      containers:
      - name: app
        image: eu.gcr.io/hits-counter-226206/hits-counter:${CIRCLE_BUILD_NUM}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "app-db-url"
              key: "databaseurl"
        - name: PORT
          value: "3000"
        ports:
          - containerPort: 3000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    metadata:
      name: migrate
    spec:
      containers:
      - name: migrate
        image: eu.gcr.io/hits-counter-226206/hits-counter:${CIRCLE_BUILD_NUM}
        command: ["/hits-counter/node_modules/.bin/db-migrate", "up"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "app-db-url"
              key: "databaseurl"
        imagePullPolicy: Never
      restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: hits-counter
  labels:
    app: hits-counter-app
spec:
  ports:
    - port: 3000
      name: hits-c-http
  selector:
    app: hits-counter-app
    tier: app
  type: NodePort
