apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hits-counter-ing
spec:
  rules:
  - http:
      paths:
      - path: /hits
        backend:
          serviceName: hits-counter
          servicePort: hits-c-http
